"""
This file was auto-generated by gen_stubs.py
"""

from __future__ import annotations

from enum import IntEnum
from typing import Literal

import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.symbol_database

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
_sym_db: google.protobuf.symbol_database.SymbolDatabase

class StartRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: int
    ARGS_FIELD_NUMBER: int
    name: str
    args: str
    def __init__(self, *, name: str = ..., args: str = ...) -> None: ...
    def ClearField(self, field_name: Literal["name", "args"]) -> None: ...

class LockStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class LockStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOCKED_FIELD_NUMBER: int
    locked: bool
    def __init__(self, *, locked: bool = ...) -> None: ...
    def ClearField(self, field_name: Literal["locked"]) -> None: ...

class AppExitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class AppLoadFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str = ...) -> None: ...
    def ClearField(self, field_name: Literal["path"]) -> None: ...

class AppButtonPressRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARGS_FIELD_NUMBER: int
    args: str
    def __init__(self, *, args: str = ...) -> None: ...
    def ClearField(self, field_name: Literal["args"]) -> None: ...

class AppButtonReleaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class AppStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: int
    state: AppState
    def __init__(self, *, state: AppState = ...) -> None: ...
    def ClearField(self, field_name: Literal["state"]) -> None: ...

class AppState(IntEnum):
    APP_CLOSED = 0
    APP_STARTED = 1

APP_CLOSED = AppState.APP_CLOSED
APP_STARTED = AppState.APP_STARTED
