"""
This file was auto-generated by gen_stubs.py at 2022-10-02T10:54
"""

from __future__ import annotations

from enum import IntEnum
from typing import Literal

import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.symbol_database

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
_sym_db: google.protobuf.symbol_database.SymbolDatabase

class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class StopSession(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class Main(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMAND_ID_FIELD_NUMBER: int
    COMMAND_STATUS_FIELD_NUMBER: int
    HAS_NEXT_FIELD_NUMBER: int
    EMPTY_FIELD_NUMBER: int
    STOP_SESSION_FIELD_NUMBER: int
    SYSTEM_PING_REQUEST_FIELD_NUMBER: int
    SYSTEM_PING_RESPONSE_FIELD_NUMBER: int
    SYSTEM_REBOOT_REQUEST_FIELD_NUMBER: int
    SYSTEM_DEVICE_INFO_REQUEST_FIELD_NUMBER: int
    SYSTEM_DEVICE_INFO_RESPONSE_FIELD_NUMBER: int
    SYSTEM_FACTORY_RESET_REQUEST_FIELD_NUMBER: int
    SYSTEM_GET_DATETIME_REQUEST_FIELD_NUMBER: int
    SYSTEM_GET_DATETIME_RESPONSE_FIELD_NUMBER: int
    SYSTEM_SET_DATETIME_REQUEST_FIELD_NUMBER: int
    SYSTEM_PLAY_AUDIOVISUAL_ALERT_REQUEST_FIELD_NUMBER: int
    SYSTEM_PROTOBUF_VERSION_REQUEST_FIELD_NUMBER: int
    SYSTEM_PROTOBUF_VERSION_RESPONSE_FIELD_NUMBER: int
    SYSTEM_UPDATE_REQUEST_FIELD_NUMBER: int
    SYSTEM_UPDATE_RESPONSE_FIELD_NUMBER: int
    SYSTEM_POWER_INFO_REQUEST_FIELD_NUMBER: int
    SYSTEM_POWER_INFO_RESPONSE_FIELD_NUMBER: int
    STORAGE_INFO_REQUEST_FIELD_NUMBER: int
    STORAGE_INFO_RESPONSE_FIELD_NUMBER: int
    STORAGE_STAT_REQUEST_FIELD_NUMBER: int
    STORAGE_STAT_RESPONSE_FIELD_NUMBER: int
    STORAGE_LIST_REQUEST_FIELD_NUMBER: int
    STORAGE_LIST_RESPONSE_FIELD_NUMBER: int
    STORAGE_READ_REQUEST_FIELD_NUMBER: int
    STORAGE_READ_RESPONSE_FIELD_NUMBER: int
    STORAGE_WRITE_REQUEST_FIELD_NUMBER: int
    STORAGE_DELETE_REQUEST_FIELD_NUMBER: int
    STORAGE_MKDIR_REQUEST_FIELD_NUMBER: int
    STORAGE_MD5SUM_REQUEST_FIELD_NUMBER: int
    STORAGE_MD5SUM_RESPONSE_FIELD_NUMBER: int
    STORAGE_RENAME_REQUEST_FIELD_NUMBER: int
    STORAGE_BACKUP_CREATE_REQUEST_FIELD_NUMBER: int
    STORAGE_BACKUP_RESTORE_REQUEST_FIELD_NUMBER: int
    APP_START_REQUEST_FIELD_NUMBER: int
    APP_LOCK_STATUS_REQUEST_FIELD_NUMBER: int
    APP_LOCK_STATUS_RESPONSE_FIELD_NUMBER: int
    APP_EXIT_REQUEST_FIELD_NUMBER: int
    APP_LOAD_FILE_REQUEST_FIELD_NUMBER: int
    APP_BUTTON_PRESS_REQUEST_FIELD_NUMBER: int
    APP_BUTTON_RELEASE_REQUEST_FIELD_NUMBER: int
    GUI_START_SCREEN_STREAM_REQUEST_FIELD_NUMBER: int
    GUI_STOP_SCREEN_STREAM_REQUEST_FIELD_NUMBER: int
    GUI_SCREEN_FRAME_FIELD_NUMBER: int
    GUI_SEND_INPUT_EVENT_REQUEST_FIELD_NUMBER: int
    GUI_START_VIRTUAL_DISPLAY_REQUEST_FIELD_NUMBER: int
    GUI_STOP_VIRTUAL_DISPLAY_REQUEST_FIELD_NUMBER: int
    GPIO_SET_PIN_MODE_FIELD_NUMBER: int
    GPIO_SET_INPUT_PULL_FIELD_NUMBER: int
    GPIO_GET_PIN_MODE_FIELD_NUMBER: int
    GPIO_GET_PIN_MODE_RESPONSE_FIELD_NUMBER: int
    GPIO_READ_PIN_FIELD_NUMBER: int
    GPIO_READ_PIN_RESPONSE_FIELD_NUMBER: int
    GPIO_WRITE_PIN_FIELD_NUMBER: int
    APP_STATE_RESPONSE_FIELD_NUMBER: int
    command_id: int
    command_status: CommandStatus
    has_next: bool
    empty: int
    stop_session: int
    system_ping_request: int
    system_ping_response: int
    system_reboot_request: int
    system_device_info_request: int
    system_device_info_response: int
    system_factory_reset_request: int
    system_get_datetime_request: int
    system_get_datetime_response: int
    system_set_datetime_request: int
    system_play_audiovisual_alert_request: int
    system_protobuf_version_request: int
    system_protobuf_version_response: int
    system_update_request: int
    system_update_response: int
    system_power_info_request: int
    system_power_info_response: int
    storage_info_request: int
    storage_info_response: int
    storage_stat_request: int
    storage_stat_response: int
    storage_list_request: int
    storage_list_response: int
    storage_read_request: int
    storage_read_response: int
    storage_write_request: int
    storage_delete_request: int
    storage_mkdir_request: int
    storage_md5sum_request: int
    storage_md5sum_response: int
    storage_rename_request: int
    storage_backup_create_request: int
    storage_backup_restore_request: int
    app_start_request: int
    app_lock_status_request: int
    app_lock_status_response: int
    app_exit_request: int
    app_load_file_request: int
    app_button_press_request: int
    app_button_release_request: int
    gui_start_screen_stream_request: int
    gui_stop_screen_stream_request: int
    gui_screen_frame: int
    gui_send_input_event_request: int
    gui_start_virtual_display_request: int
    gui_stop_virtual_display_request: int
    gpio_set_pin_mode: int
    gpio_set_input_pull: int
    gpio_get_pin_mode: int
    gpio_get_pin_mode_response: int
    gpio_read_pin: int
    gpio_read_pin_response: int
    gpio_write_pin: int
    app_state_response: int
    def __init__(self, *, command_id: int=..., command_status: CommandStatus=..., has_next: bool=..., empty: int=..., stop_session: int=..., system_ping_request: int=..., system_ping_response: int=..., system_reboot_request: int=..., system_device_info_request: int=..., system_device_info_response: int=..., system_factory_reset_request: int=..., system_get_datetime_request: int=..., system_get_datetime_response: int=..., system_set_datetime_request: int=..., system_play_audiovisual_alert_request: int=..., system_protobuf_version_request: int=..., system_protobuf_version_response: int=..., system_update_request: int=..., system_update_response: int=..., system_power_info_request: int=..., system_power_info_response: int=..., storage_info_request: int=..., storage_info_response: int=..., storage_stat_request: int=..., storage_stat_response: int=..., storage_list_request: int=..., storage_list_response: int=..., storage_read_request: int=..., storage_read_response: int=..., storage_write_request: int=..., storage_delete_request: int=..., storage_mkdir_request: int=..., storage_md5sum_request: int=..., storage_md5sum_response: int=..., storage_rename_request: int=..., storage_backup_create_request: int=..., storage_backup_restore_request: int=..., app_start_request: int=..., app_lock_status_request: int=..., app_lock_status_response: int=..., app_exit_request: int=..., app_load_file_request: int=..., app_button_press_request: int=..., app_button_release_request: int=..., gui_start_screen_stream_request: int=..., gui_stop_screen_stream_request: int=..., gui_screen_frame: int=..., gui_send_input_event_request: int=..., gui_start_virtual_display_request: int=..., gui_stop_virtual_display_request: int=..., gpio_set_pin_mode: int=..., gpio_set_input_pull: int=..., gpio_get_pin_mode: int=..., gpio_get_pin_mode_response: int=..., gpio_read_pin: int=..., gpio_read_pin_response: int=..., gpio_write_pin: int=..., app_state_response: int=...) -> None: ...
    def ClearField(self, field_name: Literal['command_id', 'command_status', 'has_next', 'empty', 'stop_session', 'system_ping_request', 'system_ping_response', 'system_reboot_request', 'system_device_info_request', 'system_device_info_response', 'system_factory_reset_request', 'system_get_datetime_request', 'system_get_datetime_response', 'system_set_datetime_request', 'system_play_audiovisual_alert_request', 'system_protobuf_version_request', 'system_protobuf_version_response', 'system_update_request', 'system_update_response', 'system_power_info_request', 'system_power_info_response', 'storage_info_request', 'storage_info_response', 'storage_stat_request', 'storage_stat_response', 'storage_list_request', 'storage_list_response', 'storage_read_request', 'storage_read_response', 'storage_write_request', 'storage_delete_request', 'storage_mkdir_request', 'storage_md5sum_request', 'storage_md5sum_response', 'storage_rename_request', 'storage_backup_create_request', 'storage_backup_restore_request', 'app_start_request', 'app_lock_status_request', 'app_lock_status_response', 'app_exit_request', 'app_load_file_request', 'app_button_press_request', 'app_button_release_request', 'gui_start_screen_stream_request', 'gui_stop_screen_stream_request', 'gui_screen_frame', 'gui_send_input_event_request', 'gui_start_virtual_display_request', 'gui_stop_virtual_display_request', 'gpio_set_pin_mode', 'gpio_set_input_pull', 'gpio_get_pin_mode', 'gpio_get_pin_mode_response', 'gpio_read_pin', 'gpio_read_pin_response', 'gpio_write_pin', 'app_state_response']) -> None: ...

class Region(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COUNTRY_CODE_FIELD_NUMBER: int
    BANDS_FIELD_NUMBER: int
    country_code: str
    bands: int
    def __init__(self, *, country_code: str=..., bands: int=...) -> None: ...
    def ClearField(self, field_name: Literal['country_code', 'bands']) -> None: ...

class Band(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_FIELD_NUMBER: int
    END_FIELD_NUMBER: int
    POWER_LIMIT_FIELD_NUMBER: int
    DUTY_CYCLE_FIELD_NUMBER: int
    start: int
    end: int
    power_limit: int
    duty_cycle: int
    def __init__(self, *, start: int=..., end: int=..., power_limit: int=..., duty_cycle: int=...) -> None: ...
    def ClearField(self, field_name: Literal['start', 'end', 'power_limit', 'duty_cycle']) -> None: ...

class CommandStatus(IntEnum):
    OK = 0
    ERROR = 1
    ERROR_DECODE = 2
    ERROR_NOT_IMPLEMENTED = 3
    ERROR_BUSY = 4
    ERROR_CONTINUOUS_COMMAND_INTERRUPTED = 14
    ERROR_INVALID_PARAMETERS = 15
    ERROR_STORAGE_NOT_READY = 5
    ERROR_STORAGE_EXIST = 6
    ERROR_STORAGE_NOT_EXIST = 7
    ERROR_STORAGE_INVALID_PARAMETER = 8
    ERROR_STORAGE_DENIED = 9
    ERROR_STORAGE_INVALID_NAME = 10
    ERROR_STORAGE_INTERNAL = 11
    ERROR_STORAGE_NOT_IMPLEMENTED = 12
    ERROR_STORAGE_ALREADY_OPEN = 13
    ERROR_STORAGE_DIR_NOT_EMPTY = 18
    ERROR_APP_CANT_START = 16
    ERROR_APP_SYSTEM_LOCKED = 17
    ERROR_APP_NOT_RUNNING = 21
    ERROR_APP_CMD_ERROR = 22
    ERROR_VIRTUAL_DISPLAY_ALREADY_STARTED = 19
    ERROR_VIRTUAL_DISPLAY_NOT_STARTED = 20
    ERROR_GPIO_MODE_INCORRECT = 58
    ERROR_GPIO_UNKNOWN_PIN_MODE = 59
OK = CommandStatus.OK
ERROR = CommandStatus.ERROR
ERROR_DECODE = CommandStatus.ERROR_DECODE
ERROR_NOT_IMPLEMENTED = CommandStatus.ERROR_NOT_IMPLEMENTED
ERROR_BUSY = CommandStatus.ERROR_BUSY
ERROR_CONTINUOUS_COMMAND_INTERRUPTED = CommandStatus.ERROR_CONTINUOUS_COMMAND_INTERRUPTED
ERROR_INVALID_PARAMETERS = CommandStatus.ERROR_INVALID_PARAMETERS
ERROR_STORAGE_NOT_READY = CommandStatus.ERROR_STORAGE_NOT_READY
ERROR_STORAGE_EXIST = CommandStatus.ERROR_STORAGE_EXIST
ERROR_STORAGE_NOT_EXIST = CommandStatus.ERROR_STORAGE_NOT_EXIST
ERROR_STORAGE_INVALID_PARAMETER = CommandStatus.ERROR_STORAGE_INVALID_PARAMETER
ERROR_STORAGE_DENIED = CommandStatus.ERROR_STORAGE_DENIED
ERROR_STORAGE_INVALID_NAME = CommandStatus.ERROR_STORAGE_INVALID_NAME
ERROR_STORAGE_INTERNAL = CommandStatus.ERROR_STORAGE_INTERNAL
ERROR_STORAGE_NOT_IMPLEMENTED = CommandStatus.ERROR_STORAGE_NOT_IMPLEMENTED
ERROR_STORAGE_ALREADY_OPEN = CommandStatus.ERROR_STORAGE_ALREADY_OPEN
ERROR_STORAGE_DIR_NOT_EMPTY = CommandStatus.ERROR_STORAGE_DIR_NOT_EMPTY
ERROR_APP_CANT_START = CommandStatus.ERROR_APP_CANT_START
ERROR_APP_SYSTEM_LOCKED = CommandStatus.ERROR_APP_SYSTEM_LOCKED
ERROR_APP_NOT_RUNNING = CommandStatus.ERROR_APP_NOT_RUNNING
ERROR_APP_CMD_ERROR = CommandStatus.ERROR_APP_CMD_ERROR
ERROR_VIRTUAL_DISPLAY_ALREADY_STARTED = CommandStatus.ERROR_VIRTUAL_DISPLAY_ALREADY_STARTED
ERROR_VIRTUAL_DISPLAY_NOT_STARTED = CommandStatus.ERROR_VIRTUAL_DISPLAY_NOT_STARTED
ERROR_GPIO_MODE_INCORRECT = CommandStatus.ERROR_GPIO_MODE_INCORRECT
ERROR_GPIO_UNKNOWN_PIN_MODE = CommandStatus.ERROR_GPIO_UNKNOWN_PIN_MODE
