"""
This file was auto-generated by gen_stubs.py
"""

from __future__ import annotations

from enum import IntEnum
from typing import Literal

import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.symbol_database

import trinn.sensors.flipper.gui_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
_sym_db: google.protobuf.symbol_database.SymbolDatabase

class ScreenFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: int
    data: bytes
    def __init__(self, *, data: bytes = ...) -> None: ...
    def ClearField(self, field_name: Literal["data"]) -> None: ...

class StartScreenStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class StopScreenStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class SendInputEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: int
    TYPE_FIELD_NUMBER: int
    key: InputKey
    type: InputType
    def __init__(self, *, key: InputKey = ..., type: InputType = ...) -> None: ...
    def ClearField(self, field_name: Literal["key", "type"]) -> None: ...

class StartVirtualDisplayRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FIRST_FRAME_FIELD_NUMBER: int
    first_frame: trinn.sensors.flipper.gui_pb2.ScreenFrame
    def __init__(self, *, first_frame: trinn.sensors.flipper.gui_pb2.ScreenFrame = ...) -> None: ...
    def ClearField(self, field_name: Literal["first_frame"]) -> None: ...

class StopVirtualDisplayRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self) -> None: ...

class InputKey(IntEnum):
    UP = 0
    DOWN = 1
    RIGHT = 2
    LEFT = 3
    OK = 4
    BACK = 5

UP = InputKey.UP
DOWN = InputKey.DOWN
RIGHT = InputKey.RIGHT
LEFT = InputKey.LEFT
OK = InputKey.OK
BACK = InputKey.BACK

class InputType(IntEnum):
    PRESS = 0
    RELEASE = 1
    SHORT = 2
    LONG = 3
    REPEAT = 4

PRESS = InputType.PRESS
RELEASE = InputType.RELEASE
SHORT = InputType.SHORT
LONG = InputType.LONG
REPEAT = InputType.REPEAT
