"""
This file was auto-generated by gen_stubs.py at 2022-10-02T10:54
"""

from __future__ import annotations

from enum import IntEnum
from typing import Literal

import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.symbol_database

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
_sym_db: google.protobuf.symbol_database.SymbolDatabase

class File(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: int
    NAME_FIELD_NUMBER: int
    SIZE_FIELD_NUMBER: int
    DATA_FIELD_NUMBER: int
    type: FileType
    name: str
    size: int
    data: str
    def __init__(self, *, type: FileType=..., name: str=..., size: int=..., data: str=...) -> None: ...
    def ClearField(self, field_name: Literal['type', 'name', 'size', 'data']) -> None: ...

class InfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['path']) -> None: ...

class InfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOTAL_SPACE_FIELD_NUMBER: int
    FREE_SPACE_FIELD_NUMBER: int
    total_space: int
    free_space: int
    def __init__(self, *, total_space: int=..., free_space: int=...) -> None: ...
    def ClearField(self, field_name: Literal['total_space', 'free_space']) -> None: ...

class StatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['path']) -> None: ...

class StatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_FIELD_NUMBER: int
    file: int
    def __init__(self, *, file: int=...) -> None: ...
    def ClearField(self, field_name: Literal['file']) -> None: ...

class ListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['path']) -> None: ...

class ListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_FIELD_NUMBER: int
    file: int
    def __init__(self, *, file: int=...) -> None: ...
    def ClearField(self, field_name: Literal['file']) -> None: ...

class ReadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['path']) -> None: ...

class ReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_FIELD_NUMBER: int
    file: int
    def __init__(self, *, file: int=...) -> None: ...
    def ClearField(self, field_name: Literal['file']) -> None: ...

class WriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    FILE_FIELD_NUMBER: int
    path: str
    file: int
    def __init__(self, *, path: str=..., file: int=...) -> None: ...
    def ClearField(self, field_name: Literal['path', 'file']) -> None: ...

class DeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    RECURSIVE_FIELD_NUMBER: int
    path: str
    recursive: bool
    def __init__(self, *, path: str=..., recursive: bool=...) -> None: ...
    def ClearField(self, field_name: Literal['path', 'recursive']) -> None: ...

class MkdirRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['path']) -> None: ...

class Md5sumRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: int
    path: str
    def __init__(self, *, path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['path']) -> None: ...

class Md5sumResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MD5SUM_FIELD_NUMBER: int
    md5sum: str
    def __init__(self, *, md5sum: str=...) -> None: ...
    def ClearField(self, field_name: Literal['md5sum']) -> None: ...

class RenameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OLD_PATH_FIELD_NUMBER: int
    NEW_PATH_FIELD_NUMBER: int
    old_path: str
    new_path: str
    def __init__(self, *, old_path: str=..., new_path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['old_path', 'new_path']) -> None: ...

class BackupCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARCHIVE_PATH_FIELD_NUMBER: int
    archive_path: str
    def __init__(self, *, archive_path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['archive_path']) -> None: ...

class BackupRestoreRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARCHIVE_PATH_FIELD_NUMBER: int
    archive_path: str
    def __init__(self, *, archive_path: str=...) -> None: ...
    def ClearField(self, field_name: Literal['archive_path']) -> None: ...

class FileType(IntEnum):
    FILE = 0
    DIR = 1
FILE = FileType.FILE
DIR = FileType.DIR
